language: python
python:
  - "3.7"
install: pip install -r requirements.txt
script: coverage run unittest_api.py
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "AKIA4HWTDJZQ3JPGBTH6"
  secret_access_key:
    secure: "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"
  region: "us-east-2"
  app: "CPS847_App"
  env: "CPS847app-env"
  bucket_name: "elasticbeanstalk-us-east-2-841182563937"
after_success: bash <(curl -s https://codecov.io/bash)

 
