deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "AKIA4HWTDJZQ7TV6S3C7"
  secret_access_key:
    secure: "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"
  region: "us-east-2"
  app: "CPS847_App"
  env: "CPS847app-env"
  bucket_name: " elasticbeanstalk-us-east-2-841182563937 "